export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const CART_EMPTY = 'CART_EMPTY'